import { v4 as uuid } from "uuid";
import { formatDate } from "../utils/authUtils";
/**
 * User Database can be added here.
 * You can add default users of your wish with different attributes
 * */

export const users = [
  {
    _id: uuid(),
    firstName: "adarsh",
    lastName: "balika",
    username: "adarsh@gmail.com",
    password: "testuser",
    createdAt: formatDate(),
    updatedAt: formatDate(),
    pic: "",
    link: "https://balika.herokuapp.com/",
    bio: "Systems Engineer @TCS | Quick Learner | Reactjs, Node.js",
    followers: [],
    following: [
      { firstName: "Ram", lastName: "Raju", username: "ram@gmail.com" },
    ],
    bookmarks: [],
    id: 1,
  },

  {
    _id: uuid(),
    firstName: "Srujana",
    lastName: "Penugonda",
    username: "srujanapenugonda@gmail.com",
    password: "srujana",
    createdAt: formatDate(),
    updatedAt: formatDate(),
    pic: "",
    link: "https://srujana-penugonda-v1.herokuapp.com/",
    bio: "Software Development Engineer II @Verizon | Ex-TCS | Passion to learn new things | Reactjs, Node.js",
    followers: [
      {
        firstName: "Karthik",
        lastName: "Bandi",
        username: "karthikbandi@gmail.com",
      },
      {
        firstName: "Devika",
        lastName: "Gill",
        username: "devikagill@gmail.com",
      },
    ],
    following: [
      { firstName: "Ram", lastName: "Raju", username: "ram@gmail.com" },
    ],
    bookmarks: [],
    id: 2,
  },
  {
    _id: uuid(),
    firstName: "Pavani",
    lastName: "Penugonda",
    username: "pavani@gmail.com",
    password: "pavani",
    createdAt: formatDate(),
    updatedAt: formatDate(),
    pic: "",
    link: "https://pavani.herokuapp.com/",
    bio: "Software Development Engineer I @Qualcomm | python, reac.js",
    followers: [],
    following: [],
    bookmarks: [],
    id: 3,
  },
  {
    _id: uuid(),
    firstName: "Ram",
    lastName: "Raju",
    username: "ram@gmail.com",
    password: "ramraju",
    createdAt: "2022-01-25T10:38:12+05:30",
    updatedAt: "2022-05-17T10:33:36+05:30",
    userHandler: "ram",
    pic: "",
    link: "https://ramspage.netlify.app",
    bio: "Aspiring Software Developer",
    followers: [
      {
        firstName: "srujana",
        lastName: "penugonda",
        username: "srujanapenugonda@gmail.com",
      },
      {
        firstName: "Adarsh",
        lastName: "Balika",
        username: "adarsh@gmail.com",
      },
      {
        firstName: "Devika",
        lastName: "Gill",
        username: "devikagill@gmail.com",
      },
    ],
    following: [
      {
        firstName: "Karthik",
        lastName: "Bandi",
        username: "karthikbandi@gmail.com",
      },
      {
        firstName: "Devika",
        lastName: "Gill",
        username: "devikagill@gmail.com",
      },
    ],
    bookmarks: [],
    id: "4",
  },
  {
    _id: uuid(),
    firstName: "Aashita",
    lastName: "Jha",
    username: "aashitajha@gmail.com",
    password: "1234asdf",
    createdAt: "2022-03-20T09:30:12+05:30",
    updatedAt: "2022-05-16T18:11:01+05:30",
    userHandler: "aashitajha",
    pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652428194/images_misbxu.jpg",
    link: "https://aashitajha.netlify.app",
    bio: "SDE-II at Invact",
    followers: [],
    following: [],
    bookmarks: [],
    id: "6",
  },
  {
    _id: uuid(),
    firstName: "Sarita",
    lastName: "Chandra",
    username: "sarithachandra@gmail.com",
    password: "1234asdf09",
    createdAt: "2022-03-19T09:30:12+05:30",
    updatedAt: "2022-05-16T18:11:01+05:30",
    userHandler: "saritachandra",
    pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652427968/images_dmm7fi.jpg",
    link: "https://sarithachandra.netlify.app",
    bio: "SDE-1 at Invact",
    followers: [],
    following: [],
    bookmarks: [],
    id: "7",
  },
  {
    _id: uuid(),
    firstName: "Karthik",
    lastName: "Bandi",
    username: "karthikbandi@gmail.com",
    password: "1234asdf09",
    createdAt: "2022-02-17T09:30:12+05:30",
    updatedAt: "2022-05-17T10:33:36+05:30",
    userHandler: "karthikbandi",
    pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652427682/images_fsjfno.jpg",
    link: "https://karthikbandi.netlify.app",
    bio: "SDE-1 at Google",
    followers: [],
    following: [
      {
        firstName: "srujana",
        lastName: "penugonda",
        username: "srujanapenugonda@gmail.com",
      },
    ],
    bookmarks: [],
    id: "8",
  },
  {
    _id: uuid(),
    firstName: "Pravin",
    lastName: "Gade",
    username: "pravingade@gmail.com",
    password: "1234asdf",
    createdAt: "2022-02-10T09:30:12+05:30",
    updatedAt: "2022-05-17T10:24:04+05:30",
    userHandler: "pravingade",
    pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652427577/ro2zurljoctvqo2kwyya.jpg",
    link: "https://pravingade.netlify.app",
    bio: "Mobile Developer",
    followers: [
      {
        firstName: "Karthik",
        lastName: "Bandi",
        username: "karthikbandi@gmail.com",
      },
    ],
    following: [],
    bookmarks: [],
    id: "9",
  },
  {
    _id: uuid(),
    firstName: "Subhash",
    lastName: "Dugar",
    username: "suhashdugar@gmail.com",
    password: "1234asdf",
    createdAt: "2022-04-09T09:30:12+05:30",
    updatedAt: "2022-05-17T11:07:27+05:30",
    userHandler: "subhashdugar",
    pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652425327/images_jt3uha.jpg",
    link: "https://subhasdugar.netlify.app",
    bio: "Web Developer",
    followers: [
      {
        firstName: "Karthik",
        lastName: "Bandi",
        username: "karthikbandi@gmail.com",
      },
    ],
    following: [
      {
        firstName: "Karthik",
        lastName: "Bandi",
        username: "karthikbandi@gmail.com",
      },
    ],
    bookmarks: [],
    id: "10",
  },
  {
    _id: uuid(),
    firstName: "Devika",
    lastName: "Gill",
    username: "devikagill@gmail.com",
    password: "1234asdf",
    createdAt: "2022-05-12T08:30:12+05:30",
    updatedAt: "2022-05-17T11:07:58+05:30",
    userHandler: "devikaGill",
    pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652425124/images_u2sypk.jpg",
    link: "https://devikagill.netlify.app",
    bio: "Web Designer",
    followers: [
      { firstName: "Ram", lastName: "Raju", username: "ram@gmail.com" },
    ],
    following: [
      { firstName: "Ram", lastName: "Raju", username: "ram@gmail.com" },
      {
        firstName: "Karthik",
        lastName: "Bandi",
        username: "karthikbandi@gmail.com",
      },
      {
        firstName: "srujana",
        lastName: "penugonda",
        username: "srujanapenugonda@gmail.com",
      },
    ],
    bookmarks: [],
    id: "11",
  },
  {
    _id: uuid(),
    firstName: "Charan",
    lastName: "Ghosh",
    username: "charanghosh@gmail.com",
    password: "1234asdf",
    createdAt: "2022-05-12T08:30:12+05:30",
    updatedAt: "2022-05-17T11:07:58+05:30",
    userHandler: "devikaGill",
    pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652425124/images_u2sypk.jpg",
    link: "https://devikagill.netlify.app",
    bio: "Web Designer",
    followers: [
      { firstName: "Ram", lastName: "Raju", username: "ram@gmail.com" },
    ],
    following: [
      { firstName: "Ram", lastName: "Raju", username: "ram@gmail.com" },
      {
        firstName: "Karthik",
        lastName: "Bandi",
        username: "karthikbandi@gmail.com",
      },
    ],
    bookmarks: [],
    id: "12",
  },
];
